//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alodc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FOOD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FOOD()
        {
            this.MENUs = new HashSet<MENU>();
        }
        
        public int ID { get; set; }

        [Required(ErrorMessage = "Please enter FoodCode")]
        [MaxLength(30, ErrorMessage = "Độ dài tối đa 30 ký tự")]
        [MinLength(3, ErrorMessage = "Độ dài ít nhất 3 ký tự")]

        public string FOOD_CODE { get; set; }

        [Required(ErrorMessage = "Please enter FoodName")]
        [MaxLength(30, ErrorMessage = "Độ dài tối đa 30 ký tự")]
        [MinLength(3, ErrorMessage = "Độ dài ít nhất 3 ký tự")]
        public string FOOD_NAME { get; set; }
        
        public int CATEGORY_ID { get; set; }
        [Required(ErrorMessage = "Please enter Description")]
        [MaxLength(30, ErrorMessage = "Độ dài tối đa 30 ký tự")]
        [MinLength(3, ErrorMessage = "Độ dài ít nhất 3 ký tự")]
        public string DESCRIPTION { get; set; }
        public int PRICE { get; set; }
        [Required(ErrorMessage = "Please enter URL")]
        public string IMAGE_URL { get; set; }
        public bool STATUS { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU> MENUs { get; set; }
    }
}
